#!/bin/sh
# File from
# http://en.gentoo-wiki.com/wiki/Improve_responsiveness_with_cgroups#Use_cgroups_automatically

# Turn on cgroups
if [ "$PS1" ] ; then
    if [ -d /sys/fs/cgroup ] ; then
        cdir=/sys/fs/cgroup
    else
        cdir=/dev/cgroup
    fi

    mkdir -p -m 0700 $cdir/user/$$ > /dev/null 2>&1
    /bin/echo $$  >  $cdir/user/$$/tasks
    /bin/echo '1' >  $cdir/user/$$/notify_on_release
fi
