#!/bin/sh
# File from
# http://en.gentoo-wiki.com/wiki/Improve_responsiveness_with_cgroups#Use_cgroups_automatically

if [ "$PS1" ] ; then
   mkdir -p -m 0700 /dev/cgroup/user/$$ > /dev/null 2>&1
   /bin/echo $$ > /dev/cgroup/user/$$/tasks
   /bin/echo '1' > /dev/cgroup/user/$$/notify_on_release
fi
